### PR TITLE
Dev->Main

### PR DESCRIPTION
**Pull request by rahulk1011**
Registration API changes. Candidate twig update.

### CODE REVIEW

**Review by rahul1091 — APPROVED** [review]

**Comment by rahul1091** [comment]
Approved

**Review by rahulk1011 — COMMENTED** [review]
Approved

**Review by rahul1091 — APPROVED** [review]
OK.

**Review by rahul1091 — APPROVED** [review]
ok. done.

**Review by rahul1091 — APPROVED** [review]

**Pull request merged**
